### ISSUE TITLE
new deck: ajax for scryfall call

### ISSUE THREAD

**Issue by lazarchitect** [thelazarbeam/Deckerator#5]
when u get the image, use the DOM to edit an existing blank img tag? or make a new tag? can JS do that?

**Comment by thelazarbeam** [comment]
i mean i just followed a tutorial lol pretty simple. Im just glad it works and didnt have any other dependencies.

**Comment by lazarchitect** [comment]
i mean i just followed a tutorial lol pretty simple. Im just glad it works and didnt have any dependencies. setAttribute is pretty spiff.
