### ISSUE TITLE
newdeck: organize page css-wise, add sql to send deck to database

### ISSUE THREAD

**Issue by lazarchitect** [thelazarbeam/Deckerator#6]
1. card image needs to be smaller, error handling for card not found, clicking on it adds to dynamic decklist on right, "save deck" button sends decklist to.....

2. new site route that sends it to the database WITH THE USERS USERID. will need to add user details to session.

**Comment by thelazarbeam** [comment]
didnt do css yet but sql is done. thought it would be harder but its actually easier haha

**Comment by lazarchitect** [comment]
didnt do css yet but sql is done. thought it would be harder but its actually easier haha
